// ui/angular/src/app/financial/tabs/payments-tab.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { PaymentService } from '../../payments/payment.service';
import { PaymentDto } from '../models';
import { BalanceDto } from '../../payments/models';

function currentMonth(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function formatEur(n: number): string {
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(n);
}

@Component({
  selector: 'app-payments-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, ProgressSpinnerModule, TranslatePipe],
  template: `
    <!-- ── Payments ── -->
    <div class="section-divider"><span class="section-label">{{ 'nav.payments' | translate }}</span></div>

    @if (balance()) {
      <div class="summary-card" style="margin-bottom:16px">
        <table class="fin-table" style="width:100%">
          <thead><tr>
            <th>{{ 'common.household' | translate }}</th>
            <th>{{ 'payments.charged' | translate }}</th>
            <th>{{ 'payments.paid' | translate }}</th>
            <th>{{ 'payments.balance' | translate }}</th>
          </tr></thead>
          <tbody>
            @for (l of balance()!.lines; track l.householdRef) {
              <tr [attr.data-testid]="'balance-row-' + l.householdRef">
                <td>{{ l.householdRef }}</td>
                <td>{{ formatEur(l.totalCharged) }}</td>
                <td>{{ formatEur(l.totalPaid) }}</td>
                <td [class.overdue]="l.balance > 0">{{ formatEur(l.balance) }}</td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    <form data-testid="payment-form" class="record-form" (ngSubmit)="onPaymentSubmit()">
      <h3 class="form-title">{{ 'payments.record' | translate }}</h3>
      <div class="form-grid">
        <div class="form-row">
          <label>{{ 'common.householdRef' | translate }}</label>
          <input type="text" [(ngModel)]="payForm.householdRef" name="payRef" required class="form-input" placeholder="e.g. H001" />
        </div>
        <div class="form-row">
          <label>{{ 'payments.amountEuro' | translate }}</label>
          <input type="number" step="0.01" min="0.01" [(ngModel)]="payForm.amountEurStr" name="payAmt" required class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'payments.periodYm' | translate }}</label>
          <input type="month" [(ngModel)]="payForm.period" name="payPer" required class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'payments.dateReceived' | translate }}</label>
          <input type="date" [(ngModel)]="payForm.dateReceived" name="payDate" required class="form-input" />
        </div>
      </div>
      <button type="submit" data-testid="payment-submit-btn" class="submit-btn" [disabled]="paySaving()">{{ 'payments.record' | translate }}</button>
      @if (payOk()) { <p data-testid="payment-submit-success" class="success-msg">{{ 'payments.recorded' | translate }}</p> }
      @if (payErr()) { <p data-testid="payment-submit-error" class="error-msg">{{ payErr() }}</p> }
    </form>

    @if (payLoading()) {
      <div class="center-state"><p-progressspinner strokeWidth="4" [style]="{width:'36px',height:'36px'}" /></div>
    } @else if (payError()) {
      <div class="error-state"><p>{{ payError() }}</p><button (click)="loadPayments()">{{ 'common.retry' | translate }}</button></div>
    } @else {
      <div class="table-scroll">
        <table class="fin-table">
          <thead><tr>
            <th>{{ 'common.period' | translate }}</th>
            <th>{{ 'common.household' | translate }}</th>
            <th>{{ 'common.amount' | translate }}</th>
            <th>{{ 'payments.dateReceived' | translate }}</th>
          </tr></thead>
          <tbody>
            @for (p of payments(); track p.id) {
              <tr [attr.data-testid]="'payment-row-' + p.id">
                <td>{{ p.period }}</td>
                <td>{{ p.householdRef }}</td>
                <td>{{ formatEur(p.amountEur) }}</td>
                <td>{{ p.dateReceived }}</td>
              </tr>
            }
            @if (payments().length === 0) {
              <tr><td colspan="4" class="empty-cell">{{ 'payments.none' | translate }}</td></tr>
            }
          </tbody>
        </table>
      </div>
    }
  `,
  styles: [`
    .section-divider { display: flex; align-items: center; margin: 24px 0 16px; gap: 12px; }
    .section-divider::before, .section-divider::after { content: ''; flex: 1; height: 1px; background: #e0e0e0; }
    .section-label { font-size: .75rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #888; white-space: nowrap; }
    .summary-card { display: flex; gap: 32px; margin-bottom: 16px; padding: 16px; background: white; border-radius: 8px; border: 1px solid #e0e0e0; flex-wrap: wrap; }
    .record-form { background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
    .form-title { margin: 0 0 12px; font-size: .9375rem; font-weight: 600; }
    .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
    @media (max-width: 480px) { .form-grid { grid-template-columns: 1fr; } }
    .form-row { display: flex; flex-direction: column; gap: 4px; }
    .form-row label { font-size: .8125rem; font-weight: 500; color: #555; }
    .form-input { padding: 7px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: .875rem; }
    .submit-btn { background: #2e6b4f; color: white; border: none; padding: 7px 18px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .submit-btn:hover { background: #245a40; }
    .submit-btn:disabled { opacity: .6; cursor: not-allowed; }
    .success-msg { color: #2e6b4f; font-weight: 500; margin: 8px 0 0; font-size: .875rem; }
    .error-msg { color: #c00; margin: 8px 0 0; font-size: .875rem; }
    .table-scroll { overflow-x: auto; }
    .fin-table { width: 100%; border-collapse: collapse; }
    .fin-table th, .fin-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: .875rem; white-space: nowrap; }
    .fin-table th { background: #f9f9f7; font-weight: 600; color: #555; }
    .empty-cell { text-align: center; color: #999; padding: 16px; white-space: normal; }
    .overdue { color: #c00; font-weight: 600; }
    .center-state { display: flex; justify-content: center; padding: 32px; }
    .error-state { display: flex; flex-direction: column; align-items: center; gap: 12px; padding: 32px; color: #c00; }
  `],
})
export class PaymentsTabComponent implements OnInit {
  private readonly paySvc = inject(PaymentService);
  private readonly t = inject(TranslateService);

  readonly formatEur = formatEur;

  // ── Payments ─────────────────────────────────────────────────────────────
  readonly payments    = signal<PaymentDto[]>([]);
  readonly balance     = signal<BalanceDto | null>(null);
  readonly payLoading  = signal(true);
  readonly payError    = signal<string | null>(null);
  readonly paySaving   = signal(false);
  readonly payOk       = signal(false);
  readonly payErr      = signal<string | null>(null);
  payForm = { householdRef: '', amountEurStr: '', period: currentMonth(), dateReceived: today() };

  ngOnInit(): void {
    this.loadPayments();
    this.loadBalance();
  }

  loadPayments(): void {
    this.payLoading.set(true); this.payError.set(null);
    this.paySvc.getAllPayments().subscribe({
      next: list => { this.payments.set(list); this.payLoading.set(false); },
      error: () => { this.payError.set(this.t.instant('payments.errLoad')); this.payLoading.set(false); },
    });
  }

  loadBalance(): void {
    this.paySvc.getBalance().subscribe({
      next: b => this.balance.set(b),
      error: () => { /* non-blocking */ },
    });
  }

  onPaymentSubmit(): void {
    this.payOk.set(false); this.payErr.set(null);
    const parsed = parseFloat(this.payForm.amountEurStr);
    if (!this.payForm.householdRef || !this.payForm.amountEurStr || isNaN(parsed) || parsed <= 0) {
      this.payErr.set(this.t.instant('payments.errInput')); return;
    }
    this.paySaving.set(true);
    this.paySvc.recordPayment({
      householdRef: this.payForm.householdRef, amountEur: parsed,
      period: this.payForm.period, dateReceived: this.payForm.dateReceived,
      idempotencyKey: crypto.randomUUID(),
    }).subscribe({
      next: () => {
        this.payOk.set(true);
        this.payForm = { householdRef: '', amountEurStr: '', period: currentMonth(), dateReceived: today() };
        this.paySaving.set(false);
        this.loadPayments();
        this.loadBalance();
      },
      error: () => { this.payErr.set(this.t.instant('payments.errRecord')); this.paySaving.set(false); },
    });
  }
}

// ui/react/src/components/financial/PaymentsTab.tsx
import { useState, useEffect, useCallback } from 'react';
import {
  Alert, Box, Button, Card, CardContent, CircularProgress,
  Divider, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography,
} from '@mui/material';
import { Refresh } from '@mui/icons-material';
import { useTranslation } from 'react-i18next';
import { getAllPayments, recordPayment, getBalance } from '../../api/payments';
import { PaymentDto, BalanceDto } from '../../types';
import { formatEur, currentMonth, today } from './util';

function SectionDivider({ label }: { label: string }) {
  return (
    <Divider sx={{ my: 1 }}>
      <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 600, letterSpacing: 1 }}>
        {label}
      </Typography>
    </Divider>
  );
}

export default function PaymentsTab() {
  const { t } = useTranslation();

  const [payments, setPayments]     = useState<PaymentDto[]>([]);
  const [balance, setBalance]       = useState<BalanceDto | null>(null);
  const [payLoad, setPayLoad]       = useState(true);
  const [payErr, setPayErr]         = useState('');
  const [payRef, setPayRef]         = useState('');
  const [payAmt, setPayAmt]         = useState('');
  const [payPer, setPayPer]         = useState(currentMonth());
  const [payDate, setPayDate]       = useState(today());
  const [paySaving, setPaySaving]   = useState(false);
  const [payOk, setPayOk]           = useState(false);
  const [payFormErr, setPayFormErr] = useState('');

  const loadPayments = useCallback(async () => {
    setPayLoad(true); setPayErr('');
    try { setPayments(await getAllPayments()); }
    catch { setPayErr(t('payments.errLoad')); }
    finally { setPayLoad(false); }
  }, [t]);

  const loadBalance = useCallback(async () => {
    try { setBalance(await getBalance()); } catch { /* non-blocking */ }
  }, []);

  useEffect(() => { loadPayments(); loadBalance(); }, [loadPayments, loadBalance]);

  const handlePaySubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setPayOk(false); setPayFormErr('');
    const parsed = parseFloat(payAmt);
    if (!payRef || !payAmt || isNaN(parsed) || parsed <= 0) { setPayFormErr(t('payments.errInput')); return; }
    setPaySaving(true);
    try {
      await recordPayment({ householdRef: payRef, amountEur: parsed, period: payPer, dateReceived: payDate, idempotencyKey: crypto.randomUUID() });
      setPayOk(true); setPayRef(''); setPayAmt(''); setPayPer(currentMonth()); setPayDate(today());
      await loadPayments(); await loadBalance();
    } catch { setPayFormErr(t('payments.errRecord')); }
    finally { setPaySaving(false); }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <SectionDivider label={t('nav.payments')} />

      {balance && (
        <Card variant="outlined">
          <CardContent sx={{ py: '12px !important' }}>
            <Typography variant="subtitle2" sx={{ fontWeight: 600, mb: 1 }}>
              {t('payments.balanceLabel', { label: balance.label })}
            </Typography>
            <Box sx={{ overflowX: 'auto' }}>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>{t('common.household')}</TableCell>
                    <TableCell align="right">{t('payments.charged')}</TableCell>
                    <TableCell align="right">{t('payments.paid')}</TableCell>
                    <TableCell align="right">{t('payments.balance')}</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {balance.lines.map(l => (
                    <TableRow key={l.householdRef} data-testid={`balance-row-${l.householdRef}`}>
                      <TableCell>{l.householdRef}</TableCell>
                      <TableCell align="right">{formatEur(l.totalCharged)}</TableCell>
                      <TableCell align="right">{formatEur(l.totalPaid)}</TableCell>
                      <TableCell align="right" sx={{ color: l.balance > 0 ? 'error.main' : 'success.main', fontWeight: 600 }}>
                        {formatEur(l.balance)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>
          </CardContent>
        </Card>
      )}

      <Card variant="outlined">
        <CardContent>
          <Typography variant="subtitle2" sx={{ fontWeight: 600, mb: 1.5 }}>{t('payments.record')}</Typography>
          <Box component="form" data-testid="payment-form" onSubmit={handlePaySubmit} sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
            <TextField label={t('common.householdRef')} value={payRef} onChange={e => setPayRef(e.target.value)} required size="small" placeholder="e.g. H001" slotProps={{ htmlInput: { 'aria-label': t('common.householdRef') } }} />
            <TextField label={t('payments.amountEuro')} type="number" slotProps={{ htmlInput: { step: '0.01', min: '0.01', 'aria-label': t('payments.amountEuro') } }} value={payAmt} onChange={e => setPayAmt(e.target.value)} required size="small" />
            <TextField label={t('payments.periodYm')} type="month" value={payPer} onChange={e => setPayPer(e.target.value)} required size="small" slotProps={{ inputLabel: { shrink: true } }} />
            <TextField label={t('payments.dateReceived')} type="date" value={payDate} onChange={e => setPayDate(e.target.value)} required size="small" slotProps={{ inputLabel: { shrink: true } }} />
            <Box sx={{ gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', gap: 1 }}>
              <Button data-testid="payment-submit-btn" type="submit" variant="contained" disabled={paySaving} size="small" sx={{ alignSelf: 'flex-start' }}>{t('payments.record')}</Button>
              {payOk && <Alert data-testid="payment-submit-success" severity="success" sx={{ py: 0 }}>{t('payments.recorded')}</Alert>}
              {payFormErr && <Alert data-testid="payment-submit-error" severity="error" sx={{ py: 0 }}>{payFormErr}</Alert>}
            </Box>
          </Box>
        </CardContent>
      </Card>

      {payLoad ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}><CircularProgress /></Box>
      ) : payErr ? (
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
          <Alert severity="error">{payErr}</Alert>
          <Button variant="outlined" startIcon={<Refresh />} onClick={loadPayments} size="small">{t('common.retry')}</Button>
        </Box>
      ) : (
        <Box sx={{ overflowX: 'auto' }}>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>{t('common.period')}</TableCell>
                <TableCell>{t('common.household')}</TableCell>
                <TableCell align="right">{t('common.amount')}</TableCell>
                <TableCell>{t('payments.dateReceived')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {payments.length === 0 ? (
                <TableRow><TableCell colSpan={4} align="center" sx={{ color: 'text.secondary', py: 3 }}>{t('payments.none')}</TableCell></TableRow>
              ) : payments.map(p => (
                <TableRow key={p.id} data-testid={`payment-row-${p.id}`}>
                  <TableCell>{p.period}</TableCell>
                  <TableCell>{p.householdRef}</TableCell>
                  <TableCell align="right">{formatEur(p.amountEur)}</TableCell>
                  <TableCell>{p.dateReceived}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Box>
      )}
    </Box>
  );
}
