// ui/angular/src/app/financial/tabs/report-tab.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { ExpenseService } from '../../expenses/expense.service';
import { AnnualReportDto } from '../../expenses/models';

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function formatEur(n: number): string {
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(n);
}

@Component({
  selector: 'app-report-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, ProgressSpinnerModule, TranslatePipe],
  template: `
    <!-- ── Annual Report ── -->
    <div class="section-divider"><span class="section-label">{{ 'annualReport.title' | translate }}</span></div>

    <!-- Record income form -->
    <form data-testid="income-form" class="record-form" (ngSubmit)="onIncomeSubmit()">
      <h3 class="form-title">{{ 'annualReport.recordIncome' | translate }}</h3>
      <div class="form-grid">
        <div class="form-row">
          <label>{{ 'annualReport.incomeCategory' | translate }}</label>
          <input type="text" [(ngModel)]="incForm.category" name="incCat" class="form-input" required />
        </div>
        <div class="form-row">
          <label>{{ 'common.description' | translate }}</label>
          <input type="text" [(ngModel)]="incForm.description" name="incDesc" class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'expenses.amountEuro' | translate }}</label>
          <input type="number" step="0.01" min="0.01" [(ngModel)]="incForm.amountEurStr" name="incAmt" required class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'annualReport.incomeDate' | translate }}</label>
          <input type="date" [(ngModel)]="incForm.incomeDate" name="incDate" required class="form-input" />
        </div>
      </div>
      <button type="submit" data-testid="income-submit-btn" class="submit-btn" [disabled]="incSaving()">{{ 'annualReport.recordIncome' | translate }}</button>
      @if (incOk()) { <p data-testid="income-submit-success" class="success-msg">{{ 'annualReport.incomeRecorded' | translate }}</p> }
      @if (incErr()) { <p data-testid="income-submit-error" class="error-msg">{{ incErr() }}</p> }
    </form>

    <!-- Year picker + load -->
    <div class="period-row" style="margin-bottom:12px">
      <label class="period-label">{{ 'annualReport.yearLabel' | translate }}</label>
      <input type="number" [(ngModel)]="reportYear" min="2000" max="2100" class="period-input" style="width:90px" />
      <button class="submit-btn" (click)="loadAnnualReport()" [disabled]="repLoad()">{{ 'common.load' | translate }}</button>
      <button class="submit-btn xlsx-btn" (click)="downloadXlsx()" [disabled]="xlsxLoad()">{{ 'annualReport.downloadExcel' | translate }}</button>
      @if (repLoad() || xlsxLoad()) { <p-progressspinner strokeWidth="4" [style]="{width:'24px',height:'24px'}" /> }
    </div>
    @if (repErr()) { <p class="error-msg">{{ repErr() }}</p> }

    @if (report()) {
      <div class="table-scroll">
        <table class="fin-table rep-table">
          <thead>
            <tr>
              <th class="rep-label-col">{{ 'annualReport.title' | translate }}</th>
              @for (m of report()!.months; track m) { <th class="rep-month-col">{{ m }}</th> }
              <th class="rep-total-col">{{ 'annualReport.total' | translate }}</th>
            </tr>
          </thead>
          <tbody>
            <!-- Income section -->
            <tr class="rep-section-row">
              <td [attr.colspan]="report()!.months.length + 2" class="rep-section-label">{{ 'annualReport.income' | translate }}</td>
            </tr>
            <!-- Maintenance fees -->
            <tr>
              <td class="rep-label-cell">{{ 'annualReport.maintenanceFees' | translate }}</td>
              @for (v of report()!.maintenanceFees.byMonth; track $index) {
                <td class="rep-num-cell">{{ v !== 0 ? formatEur(v) : '' }}</td>
              }
              <td class="rep-num-cell rep-total-cell">{{ formatEur(report()!.maintenanceFees.total) }}</td>
            </tr>
            <!-- Other income rows -->
            @for (line of report()!.otherIncome; track line.category) {
              <tr>
                <td class="rep-label-cell rep-indent">{{ line.category }}</td>
                @for (v of line.byMonth; track $index) {
                  <td class="rep-num-cell">{{ v !== 0 ? formatEur(v) : '' }}</td>
                }
                <td class="rep-num-cell rep-total-cell">{{ formatEur(line.total) }}</td>
              </tr>
            }

            <!-- Expenses section -->
            <tr class="rep-section-row">
              <td [attr.colspan]="report()!.months.length + 2" class="rep-section-label">{{ 'annualReport.expenses' | translate }}</td>
            </tr>
            @for (parent of report()!.expenses; track parent.parentCategory) {
              @for (sub of parent.subCategories; track sub.name; let fi = $first) {
                <tr>
                  <td class="rep-label-cell">
                    @if (fi) { <span class="rep-parent-label">{{ parent.parentCategory }} /</span> }
                    <span class="rep-indent">{{ sub.name }}</span>
                  </td>
                  @for (v of sub.byMonth; track $index) {
                    <td class="rep-num-cell">{{ v !== 0 ? formatEur(v) : '' }}</td>
                  }
                  <td class="rep-num-cell rep-total-cell">{{ formatEur(sub.total) }}</td>
                </tr>
              }
            }

            <!-- Period result -->
            <tr class="rep-result-row">
              <td class="rep-label-cell">{{ 'annualReport.periodResult' | translate }}</td>
              @for (v of report()!.periodResultByMonth; track $index) {
                <td class="rep-num-cell" [class.rep-positive]="v > 0" [class.rep-negative]="v < 0">{{ formatEur(v) }}</td>
              }
              <td class="rep-num-cell rep-total-cell" [class.rep-positive]="report()!.periodResultTotal > 0" [class.rep-negative]="report()!.periodResultTotal < 0">
                {{ formatEur(report()!.periodResultTotal) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    }
  `,
  styles: [`
    .section-divider { display: flex; align-items: center; margin: 24px 0 16px; gap: 12px; }
    .section-divider::before, .section-divider::after { content: ''; flex: 1; height: 1px; background: #e0e0e0; }
    .section-label { font-size: .75rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #888; white-space: nowrap; }
    .record-form { background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
    .form-title { margin: 0 0 12px; font-size: .9375rem; font-weight: 600; }
    .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
    @media (max-width: 480px) { .form-grid { grid-template-columns: 1fr; } }
    .form-row { display: flex; flex-direction: column; gap: 4px; }
    .form-row label { font-size: .8125rem; font-weight: 500; color: #555; }
    .form-input { padding: 7px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: .875rem; }
    .submit-btn { background: #2e6b4f; color: white; border: none; padding: 7px 18px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .submit-btn:hover { background: #245a40; }
    .submit-btn:disabled { opacity: .6; cursor: not-allowed; }
    .xlsx-btn { background: #1d6b21; }
    .xlsx-btn:hover { background: #155218; }
    .success-msg { color: #2e6b4f; font-weight: 500; margin: 8px 0 0; font-size: .875rem; }
    .error-msg { color: #c00; margin: 8px 0 0; font-size: .875rem; }
    .period-row { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }
    .period-label { font-weight: 500; }
    .period-input { padding: 6px 8px; border-radius: 4px; border: 1px solid #ccc; font-size: 14px; }
    .table-scroll { overflow-x: auto; }
    .fin-table { width: 100%; border-collapse: collapse; }
    .fin-table th, .fin-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: .875rem; white-space: nowrap; }
    .fin-table th { background: #f9f9f7; font-weight: 600; color: #555; }
    .rep-table { font-size: .8125rem; }
    .rep-label-col { min-width: 180px; }
    .rep-month-col { min-width: 72px; text-align: right; }
    .rep-total-col { min-width: 80px; text-align: right; }
    .rep-label-cell { font-size: .8125rem; }
    .rep-num-cell { text-align: right; font-variant-numeric: tabular-nums; }
    .rep-total-cell { font-weight: 600; }
    .rep-section-row td { background: #f0f4f1; font-weight: 700; font-size: .75rem; text-transform: uppercase; letter-spacing: .05em; color: #555; padding: 6px 12px; }
    .rep-section-label { }
    .rep-indent { padding-left: 12px; }
    .rep-parent-label { color: #888; font-size: .75rem; margin-right: 4px; }
    .rep-result-row td { background: #e8f0ec; font-weight: 700; border-top: 2px solid #2e6b4f; }
    .rep-positive { color: #2e6b4f; }
    .rep-negative { color: #c00; }
  `],
})
export class ReportTabComponent implements OnInit {
  private readonly expSvc = inject(ExpenseService);
  private readonly t = inject(TranslateService);

  readonly formatEur = formatEur;

  // ── Annual report ─────────────────────────────────────────────────────────
  reportYear = new Date().getFullYear();
  readonly report    = signal<AnnualReportDto | null>(null);
  readonly repLoad   = signal(false);
  readonly repErr    = signal<string | null>(null);
  readonly xlsxLoad  = signal(false);
  readonly incSaving = signal(false);
  readonly incOk     = signal(false);
  readonly incErr    = signal<string | null>(null);
  incForm = { category: '', description: '', amountEurStr: '', incomeDate: today() };

  ngOnInit(): void {
    // Report is loaded on demand via the year picker button; no auto-load needed.
  }

  loadAnnualReport(): void {
    this.repLoad.set(true); this.repErr.set(null);
    this.expSvc.getAnnualReport(this.reportYear).subscribe({
      next: r => { this.report.set(r); this.repLoad.set(false); },
      error: () => { this.repErr.set(this.t.instant('annualReport.errLoad')); this.repLoad.set(false); },
    });
  }

  downloadXlsx(): void {
    this.xlsxLoad.set(true);
    this.expSvc.downloadAnnualReportXlsx(this.reportYear).subscribe({
      next: blob => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `annual-report-${this.reportYear}.xlsx`;
        a.click(); URL.revokeObjectURL(url);
        this.xlsxLoad.set(false);
      },
      error: () => { this.repErr.set(this.t.instant('annualReport.errLoad')); this.xlsxLoad.set(false); },
    });
  }

  onIncomeSubmit(): void {
    this.incOk.set(false); this.incErr.set(null);
    const parsed = parseFloat(this.incForm.amountEurStr);
    if (!this.incForm.amountEurStr || isNaN(parsed) || parsed <= 0) {
      this.incErr.set(this.t.instant('annualReport.errAmount')); return;
    }
    this.incSaving.set(true);
    this.expSvc.recordIncome({
      category: this.incForm.category, description: this.incForm.description,
      amountEur: parsed, incomeDate: this.incForm.incomeDate, idempotencyKey: crypto.randomUUID(),
    }).subscribe({
      next: () => {
        this.incOk.set(true);
        this.incForm = { category: '', description: '', amountEurStr: '', incomeDate: today() };
        this.incSaving.set(false);
      },
      error: () => { this.incErr.set(this.t.instant('annualReport.errRecord')); this.incSaving.set(false); },
    });
  }
}

// ui/react/src/components/financial/ReportTab.tsx
import React, { useState, useCallback } from 'react';
import {
  Alert, Box, Button, Card, CardContent, CircularProgress,
  Divider, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography,
} from '@mui/material';
import { useTranslation } from 'react-i18next';
import { recordIncome, getAnnualReport, downloadAnnualReportXlsx } from '../../api/expenses';
import { AnnualReportDto } from '../../types';
import { formatEur, today } from './util';

function SectionDivider({ label }: { label: string }) {
  return (
    <Divider sx={{ my: 1 }}>
      <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 600, letterSpacing: 1 }}>
        {label}
      </Typography>
    </Divider>
  );
}

export default function ReportTab() {
  const { t } = useTranslation();

  const [reportYear, setReportYear]   = useState(new Date().getFullYear());
  const [report, setReport]           = useState<AnnualReportDto | null>(null);
  const [repLoad, setRepLoad]         = useState(false);
  const [repErr, setRepErr]           = useState('');
  const [xlsxLoad, setXlsxLoad]       = useState(false);
  const [incCategory, setIncCategory] = useState('');
  const [incDesc, setIncDesc]         = useState('');
  const [incAmt, setIncAmt]           = useState('');
  const [incDate, setIncDate]         = useState(today());
  const [incSaving, setIncSaving]     = useState(false);
  const [incOk, setIncOk]             = useState(false);
  const [incFormErr, setIncFormErr]   = useState('');

  const loadReport = useCallback(async () => {
    setRepLoad(true); setRepErr('');
    try { setReport(await getAnnualReport(reportYear)); }
    catch { setRepErr(t('annualReport.errLoad')); }
    finally { setRepLoad(false); }
  }, [reportYear, t]);

  const handleDownloadXlsx = useCallback(async () => {
    setXlsxLoad(true);
    try { await downloadAnnualReportXlsx(reportYear); }
    catch { setRepErr(t('annualReport.errLoad')); }
    finally { setXlsxLoad(false); }
  }, [reportYear, t]);

  const handleIncSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setIncOk(false); setIncFormErr('');
    const parsed = parseFloat(incAmt);
    if (!incCategory || !incAmt || isNaN(parsed) || parsed <= 0) { setIncFormErr(t('annualReport.errAmount')); return; }
    setIncSaving(true);
    try {
      await recordIncome({ category: incCategory, description: incDesc, amountEur: parsed, incomeDate: incDate, idempotencyKey: crypto.randomUUID() });
      setIncOk(true); setIncCategory(''); setIncDesc(''); setIncAmt(''); setIncDate(today());
      if (report) await loadReport();
    } catch { setIncFormErr(t('annualReport.errRecord')); }
    finally { setIncSaving(false); }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <SectionDivider label={t('annualReport.title')} />

      {/* Record income form */}
      <Card variant="outlined">
        <CardContent>
          <Typography variant="subtitle2" sx={{ fontWeight: 600, mb: 1.5 }}>{t('annualReport.recordIncome')}</Typography>
          <Box component="form" data-testid="income-form" onSubmit={handleIncSubmit} sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
            <TextField label={t('annualReport.incomeCategory')} value={incCategory} onChange={e => setIncCategory(e.target.value)} required size="small" />
            <TextField label={t('common.description')} value={incDesc} onChange={e => setIncDesc(e.target.value)} size="small" />
            <TextField label={t('expenses.amountEuro')} type="number" slotProps={{ htmlInput: { step: '0.01', min: '0.01' } }} value={incAmt} onChange={e => setIncAmt(e.target.value)} required size="small" />
            <TextField label={t('annualReport.incomeDate')} type="date" value={incDate} onChange={e => setIncDate(e.target.value)} required size="small" slotProps={{ inputLabel: { shrink: true } }} />
            <Box sx={{ gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', gap: 1 }}>
              <Button data-testid="income-submit-btn" type="submit" variant="contained" disabled={incSaving} size="small" sx={{ alignSelf: 'flex-start' }}>{t('annualReport.recordIncome')}</Button>
              {incOk && <Alert data-testid="income-submit-success" severity="success" sx={{ py: 0 }}>{t('annualReport.incomeRecorded')}</Alert>}
              {incFormErr && <Alert data-testid="income-submit-error" severity="error" sx={{ py: 0 }}>{incFormErr}</Alert>}
            </Box>
          </Box>
        </CardContent>
      </Card>

      {/* Year picker + load button */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
        <Typography variant="subtitle1" sx={{ fontWeight: 500 }}>{t('annualReport.yearLabel')}</Typography>
        <TextField
          type="number"
          value={reportYear}
          onChange={e => setReportYear(parseInt(e.target.value, 10))}
          size="small"
          slotProps={{ htmlInput: { min: 2000, max: 2100, style: { width: 90 } } }}
        />
        <Button variant="outlined" size="small" onClick={loadReport} disabled={repLoad}>{t('common.load')}</Button>
        <Button variant="outlined" size="small" onClick={handleDownloadXlsx} disabled={xlsxLoad}>{t('annualReport.downloadExcel')}</Button>
        {(repLoad || xlsxLoad) && <CircularProgress size={18} />}
      </Box>

      {repErr && <Alert severity="error">{repErr}</Alert>}

      {report && (
        <Box sx={{ overflowX: 'auto' }}>
          <Table size="small" sx={{ minWidth: 900 }}>
            <TableHead>
              <TableRow sx={{ bgcolor: 'grey.100' }}>
                <TableCell sx={{ fontWeight: 700 }}>{report.year}</TableCell>
                {report.months.map(m => <TableCell key={m} align="right" sx={{ fontWeight: 600, fontSize: '0.75rem' }}>{m.slice(5)}</TableCell>)}
                <TableCell align="right" sx={{ fontWeight: 700 }}>{t('annualReport.total')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {/* Income section header */}
              <TableRow sx={{ bgcolor: 'success.50' }}>
                <TableCell colSpan={14} sx={{ fontWeight: 700, color: 'success.dark', py: 0.5 }}>{t('annualReport.income')}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell sx={{ pl: 3 }}>{t('annualReport.maintenanceFees')}</TableCell>
                {report.maintenanceFees.byMonth.map((v, i) => <TableCell key={i} align="right">{v > 0 ? formatEur(v) : '—'}</TableCell>)}
                <TableCell align="right" sx={{ fontWeight: 600 }}>{formatEur(report.maintenanceFees.total)}</TableCell>
              </TableRow>
              {report.otherIncome.map(line => (
                <TableRow key={line.category}>
                  <TableCell sx={{ pl: 3 }}>{line.category}</TableCell>
                  {line.byMonth.map((v, i) => <TableCell key={i} align="right">{v > 0 ? formatEur(v) : '—'}</TableCell>)}
                  <TableCell align="right" sx={{ fontWeight: 600 }}>{formatEur(line.total)}</TableCell>
                </TableRow>
              ))}

              {/* Expenses section header */}
              <TableRow sx={{ bgcolor: 'error.50' }}>
                <TableCell colSpan={14} sx={{ fontWeight: 700, color: 'error.dark', py: 0.5 }}>{t('annualReport.expenses')}</TableCell>
              </TableRow>
              {report.expenses.map(pg => (
                <React.Fragment key={pg.parentCategory}>
                  <TableRow sx={{ bgcolor: 'grey.50' }}>
                    <TableCell sx={{ fontWeight: 600, pl: 2 }}>{pg.parentCategory}</TableCell>
                    {Array(12).fill(null).map((_, i) => (
                      <TableCell key={i} align="right" sx={{ fontWeight: 600 }}>
                        {pg.subCategories.reduce((s, c) => s + (c.byMonth[i] ?? 0), 0) > 0
                          ? formatEur(pg.subCategories.reduce((s, c) => s + (c.byMonth[i] ?? 0), 0))
                          : '—'}
                      </TableCell>
                    ))}
                    <TableCell align="right" sx={{ fontWeight: 600 }}>
                      {formatEur(pg.subCategories.reduce((s, c) => s + c.total, 0))}
                    </TableCell>
                  </TableRow>
                  {pg.subCategories.map(sub => (
                    <TableRow key={sub.name}>
                      <TableCell sx={{ pl: 4, color: 'text.secondary', fontSize: '0.8125rem' }}>{sub.name}</TableCell>
                      {sub.byMonth.map((v, i) => <TableCell key={i} align="right" sx={{ fontSize: '0.8125rem' }}>{v > 0 ? formatEur(v) : '—'}</TableCell>)}
                      <TableCell align="right" sx={{ fontWeight: 500 }}>{formatEur(sub.total)}</TableCell>
                    </TableRow>
                  ))}
                </React.Fragment>
              ))}

              {/* Period result */}
              <TableRow sx={{ bgcolor: 'primary.50', borderTop: '2px solid', borderColor: 'divider' }}>
                <TableCell sx={{ fontWeight: 700 }}>{t('annualReport.periodResult')}</TableCell>
                {report.periodResultByMonth.map((v, i) => (
                  <TableCell key={i} align="right" sx={{ fontWeight: 600, color: v >= 0 ? 'success.main' : 'error.main' }}>
                    {formatEur(v)}
                  </TableCell>
                ))}
                <TableCell align="right" sx={{ fontWeight: 700, color: report.periodResultTotal >= 0 ? 'success.main' : 'error.main' }}>
                  {formatEur(report.periodResultTotal)}
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </Box>
      )}
    </Box>
  );
}
