// ui/react/src/components/financial/FeesTab.tsx
import React, { useState, useEffect, useCallback } from 'react';
import {
  Alert, Box, Button, Card, CardContent, CircularProgress,
  Divider, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography,
} from '@mui/material';
import { Refresh } from '@mui/icons-material';
import { useTranslation } from 'react-i18next';
import { getAllCharges, recordCharge } from '../../api/maintenanceFees';
import { getBalance } from '../../api/payments';
import { ChargeDto } from '../../types';
import { formatEur, currentMonth } from './util';

function SectionDivider({ label }: { label: string }) {
  return (
    <Divider sx={{ my: 1 }}>
      <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 600, letterSpacing: 1 }}>
        {label}
      </Typography>
    </Divider>
  );
}

export default function FeesTab() {
  const { t } = useTranslation();

  const [charges, setCharges]       = useState<ChargeDto[]>([]);
  const [outstanding, setOutstanding] = useState<Map<string, number>>(new Map());
  const [feesLoad, setFeesLoad]     = useState(true);
  const [feesErr, setFeesErr]       = useState('');
  const [feeRef, setFeeRef]         = useState('');
  const [feeAmt, setFeeAmt]         = useState('');
  const [feeDesc, setFeeDesc]       = useState('');
  const [feePer, setFeePer]         = useState(currentMonth());
  const [feeSaving, setFeeSaving]   = useState(false);
  const [feeOk, setFeeOk]           = useState(false);
  const [feeFormErr, setFeeFormErr] = useState('');

  const loadFees = useCallback(async () => {
    setFeesLoad(true); setFeesErr('');
    try {
      const [chargesData, balanceData] = await Promise.all([
        getAllCharges(),
        getBalance().catch(() => null),
      ]);
      setCharges(chargesData);
      if (balanceData) {
        setOutstanding(new Map(balanceData.lines.map(l => [l.householdRef, l.balance])));
      }
    }
    catch { setFeesErr(t('fees.errLoad')); }
    finally { setFeesLoad(false); }
  }, [t]);

  useEffect(() => { loadFees(); }, [loadFees]);

  const handleFeeSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setFeeOk(false); setFeeFormErr('');
    const parsed = parseFloat(feeAmt);
    if (!feeRef || !feeAmt || isNaN(parsed) || parsed <= 0) { setFeeFormErr(t('fees.errInput')); return; }
    setFeeSaving(true);
    try {
      await recordCharge(feeRef, { amountEur: parsed, description: feeDesc, period: feePer, idempotencyKey: crypto.randomUUID() });
      setFeeOk(true); setFeeRef(''); setFeeAmt(''); setFeeDesc(''); setFeePer(currentMonth());
      await loadFees();
    } catch { setFeeFormErr(t('fees.errRecord')); }
    finally { setFeeSaving(false); }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <SectionDivider label={t('nav.fees')} />

      <Card variant="outlined">
        <CardContent>
          <Typography variant="subtitle2" sx={{ fontWeight: 600, mb: 1.5 }}>{t('fees.record')}</Typography>
          <Box component="form" data-testid="fee-form" onSubmit={handleFeeSubmit} sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
            <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
              <TextField label={t('common.householdRef')} value={feeRef} onChange={e => setFeeRef(e.target.value)} required size="small" placeholder="e.g. H001" />
              <TextField label={t('fees.amountEuro')} type="number" slotProps={{ htmlInput: { step: '0.01', min: '0.01' } }} value={feeAmt} onChange={e => setFeeAmt(e.target.value)} required size="small" />
              <TextField label={t('common.description')} value={feeDesc} onChange={e => setFeeDesc(e.target.value)} size="small" />
              <TextField label={t('fees.periodYm')} type="month" value={feePer} onChange={e => setFeePer(e.target.value)} required size="small" slotProps={{ inputLabel: { shrink: true } }} />
            </Box>
            <Button data-testid="fee-submit-btn" type="submit" variant="contained" disabled={feeSaving} size="small" sx={{ alignSelf: 'flex-start' }}>{t('fees.record')}</Button>
            {feeOk && <Alert data-testid="fee-submit-success" severity="success" sx={{ py: 0 }}>{t('fees.recorded')}</Alert>}
            {feeFormErr && <Alert data-testid="fee-submit-error" severity="error" sx={{ py: 0 }}>{feeFormErr}</Alert>}
          </Box>
        </CardContent>
      </Card>

      {feesLoad ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}><CircularProgress /></Box>
      ) : feesErr ? (
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
          <Alert severity="error">{feesErr}</Alert>
          <Button variant="outlined" startIcon={<Refresh />} onClick={loadFees} size="small">{t('common.retry')}</Button>
        </Box>
      ) : (
        <Box sx={{ overflowX: 'auto' }}>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>{t('common.period')}</TableCell>
                <TableCell>{t('common.household')}</TableCell>
                <TableCell>{t('common.description')}</TableCell>
                <TableCell align="right">{t('common.amount')}</TableCell>
                <TableCell>{t('fees.chargedAt')}</TableCell>
                <TableCell align="right">{t('finance.outstanding')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {charges.length === 0 ? (
                <TableRow><TableCell colSpan={6} align="center" sx={{ color: 'text.secondary', py: 3 }}>{t('fees.none')}</TableCell></TableRow>
              ) : charges.map(c => (
                <TableRow key={c.id} data-testid={`charge-row-${c.id}`}>
                  <TableCell>{c.period}</TableCell>
                  <TableCell>{c.householdRef}</TableCell>
                  <TableCell>{c.description}</TableCell>
                  <TableCell align="right">{formatEur(c.amountEur)}</TableCell>
                  <TableCell>{c.chargedAt.slice(0, 10)}</TableCell>
                  <TableCell align="right" data-testid={`outstanding-${c.id}`}>
                    {outstanding.has(c.householdRef) ? formatEur(outstanding.get(c.householdRef)!) : '—'}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Box>
      )}
    </Box>
  );
}

// ui/angular/src/app/financial/tabs/fees-tab.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { MaintenanceFeeService } from '../../maintenance-fees/maintenance-fee.service';
import { PaymentService } from '../../payments/payment.service';
import { ChargeDto } from '../models';

function currentMonth(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function formatEur(n: number): string {
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(n);
}

@Component({
  selector: 'app-fees-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, ProgressSpinnerModule, TranslatePipe],
  template: `
    <!-- ── Maintenance fees ── -->
    <div class="section-divider"><span class="section-label">{{ 'nav.fees' | translate }}</span></div>

    <form data-testid="fee-form" class="record-form" (ngSubmit)="onFeeSubmit()">
      <h3 class="form-title">{{ 'fees.record' | translate }}</h3>
      <div class="form-grid">
        <div class="form-row">
          <label>{{ 'common.householdRef' | translate }}</label>
          <input type="text" [(ngModel)]="feeForm.householdRef" name="feeRef" required class="form-input" placeholder="e.g. H001" />
        </div>
        <div class="form-row">
          <label>{{ 'fees.amountEuro' | translate }}</label>
          <input type="number" step="0.01" min="0.01" [(ngModel)]="feeForm.amountEurStr" name="feeAmt" required class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'common.description' | translate }}</label>
          <input type="text" [(ngModel)]="feeForm.description" name="feeDesc" class="form-input" />
        </div>
        <div class="form-row">
          <label>{{ 'fees.periodYm' | translate }}</label>
          <input type="month" [(ngModel)]="feeForm.period" name="feePer" required class="form-input" />
        </div>
      </div>
      <button type="submit" data-testid="fee-submit-btn" class="submit-btn" [disabled]="feeSaving()">{{ 'fees.record' | translate }}</button>
      @if (feeOk()) { <p data-testid="fee-submit-success" class="success-msg">{{ 'fees.recorded' | translate }}</p> }
      @if (feeErr()) { <p data-testid="fee-submit-error" class="error-msg">{{ feeErr() }}</p> }
    </form>

    @if (feesLoading()) {
      <div class="center-state"><p-progressspinner strokeWidth="4" [style]="{width:'36px',height:'36px'}" /></div>
    } @else if (feesError()) {
      <div class="error-state"><p>{{ feesError() }}</p><button (click)="loadFees()">{{ 'common.retry' | translate }}</button></div>
    } @else {
      <div class="table-scroll">
        <table class="fin-table">
          <thead><tr>
            <th>{{ 'common.period' | translate }}</th>
            <th>{{ 'common.household' | translate }}</th>
            <th>{{ 'common.description' | translate }}</th>
            <th>{{ 'common.amount' | translate }}</th>
            <th>{{ 'fees.chargedAt' | translate }}</th>
            <th>{{ 'finance.outstanding' | translate }}</th>
          </tr></thead>
          <tbody>
            @for (c of charges(); track c.id) {
              <tr [attr.data-testid]="'charge-row-' + c.id">
                <td>{{ c.period }}</td>
                <td>{{ c.householdRef }}</td>
                <td>{{ c.description }}</td>
                <td>{{ formatEur(c.amountEur) }}</td>
                <td>{{ c.chargedAt | date:'yyyy-MM-dd' }}</td>
                <td [attr.data-testid]="'charge-outstanding-' + c.id">{{ formatEur(outstandingFor(c.householdRef)) }}</td>
              </tr>
            }
            @if (charges().length === 0) {
              <tr><td colspan="6" class="empty-cell">{{ 'fees.none' | translate }}</td></tr>
            }
          </tbody>
        </table>
      </div>
    }
  `,
  styles: [`
    .section-divider { display: flex; align-items: center; margin: 24px 0 16px; gap: 12px; }
    .section-divider::before, .section-divider::after { content: ''; flex: 1; height: 1px; background: #e0e0e0; }
    .section-label { font-size: .75rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #888; white-space: nowrap; }
    .record-form { background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
    .form-title { margin: 0 0 12px; font-size: .9375rem; font-weight: 600; }
    .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
    @media (max-width: 480px) { .form-grid { grid-template-columns: 1fr; } }
    .form-row { display: flex; flex-direction: column; gap: 4px; }
    .form-row label { font-size: .8125rem; font-weight: 500; color: #555; }
    .form-input { padding: 7px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: .875rem; }
    .submit-btn { background: #2e6b4f; color: white; border: none; padding: 7px 18px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .submit-btn:hover { background: #245a40; }
    .submit-btn:disabled { opacity: .6; cursor: not-allowed; }
    .success-msg { color: #2e6b4f; font-weight: 500; margin: 8px 0 0; font-size: .875rem; }
    .error-msg { color: #c00; margin: 8px 0 0; font-size: .875rem; }
    .table-scroll { overflow-x: auto; }
    .fin-table { width: 100%; border-collapse: collapse; }
    .fin-table th, .fin-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: .875rem; white-space: nowrap; }
    .fin-table th { background: #f9f9f7; font-weight: 600; color: #555; }
    .empty-cell { text-align: center; color: #999; padding: 16px; white-space: normal; }
    .center-state { display: flex; justify-content: center; padding: 32px; }
    .error-state { display: flex; flex-direction: column; align-items: center; gap: 12px; padding: 32px; color: #c00; }
  `],
})
export class FeesTabComponent implements OnInit {
  private readonly feeSvc = inject(MaintenanceFeeService);
  private readonly paySvc = inject(PaymentService);
  private readonly t = inject(TranslateService);

  readonly formatEur = formatEur;

  // ── Maintenance fees ──────────────────────────────────────────────────────
  readonly charges     = signal<ChargeDto[]>([]);
  readonly feesLoading = signal(true);
  readonly feesError   = signal<string | null>(null);
  readonly feeSaving   = signal(false);
  readonly feeOk       = signal(false);
  readonly feeErr      = signal<string | null>(null);
  readonly balanceMap  = signal<Map<string, number>>(new Map());
  feeForm = { householdRef: '', amountEurStr: '', description: '', period: currentMonth() };

  ngOnInit(): void {
    this.loadFees();
    this.loadBalance();
  }

  loadFees(): void {
    this.feesLoading.set(true); this.feesError.set(null);
    this.feeSvc.getAllCharges().subscribe({
      next: list => { this.charges.set(list); this.feesLoading.set(false); },
      error: () => { this.feesError.set(this.t.instant('fees.errLoad')); this.feesLoading.set(false); },
    });
  }

  loadBalance(): void {
    this.paySvc.getBalance().subscribe({
      next: b => this.balanceMap.set(new Map(b.lines.map(l => [l.householdRef, l.balance]))),
      error: () => { /* non-blocking — Outstanding column just shows 0 */ },
    });
  }

  outstandingFor(householdRef: string): number {
    return this.balanceMap().get(householdRef) ?? 0;
  }

  onFeeSubmit(): void {
    this.feeOk.set(false); this.feeErr.set(null);
    const parsed = parseFloat(this.feeForm.amountEurStr);
    if (!this.feeForm.householdRef || !this.feeForm.amountEurStr || isNaN(parsed) || parsed <= 0) {
      this.feeErr.set(this.t.instant('fees.errInput')); return;
    }
    this.feeSaving.set(true);
    this.feeSvc.recordCharge(this.feeForm.householdRef, {
      amountEur: parsed, description: this.feeForm.description,
      period: this.feeForm.period, idempotencyKey: crypto.randomUUID(),
    }).subscribe({
      next: () => {
        this.feeOk.set(true);
        this.feeForm = { householdRef: '', amountEurStr: '', description: '', period: currentMonth() };
        this.feeSaving.set(false);
        this.loadFees();
      },
      error: () => { this.feeErr.set(this.t.instant('fees.errRecord')); this.feeSaving.set(false); },
    });
  }
}
