// ui/react/src/components/financial/OutcomeTab.tsx
import React, { useState, useEffect, useCallback } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider,
  Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography,
} from '@mui/material';
import { Refresh } from '@mui/icons-material';
import { useTranslation } from 'react-i18next';
import { getExpenses, recordExpense, scanInvoice } from '../../api/expenses';
import { ExpenseListItemDto } from '../../types';
import { CounterpartyDto } from '../../api/counterparties';
import CounterpartyPicker from './CounterpartyPicker';
import { formatEur, today } from './util';

export default function OutcomeTab() {
  const { t } = useTranslation();

  // Single shared bill form (manual + scan target)
  const [amount, setAmount]           = useState('');
  const [desc, setDesc]               = useState('');
  const [counterparty, setCounterparty] = useState<CounterpartyDto | null>(null);
  const [date, setDate]               = useState(today());
  const [confidence, setConf]         = useState<number | null>(null); // null = manual / nothing extracted
  const [scanning, setScanning]       = useState(false);
  const [scanErr, setScanErr]         = useState('');
  const [scanNote, setScanNote]       = useState('');
  const [saving, setSaving]           = useState(false);
  const [ok, setOk]                   = useState(false);
  const [formErr, setFormErr]         = useState('');

  const [expenses, setExpenses] = useState<ExpenseListItemDto[]>([]);
  const [expLoad, setExpLoad]   = useState(true);
  const [expErr, setExpErr]     = useState('');

  const loadExpenses = useCallback(async () => {
    setExpLoad(true); setExpErr('');
    try { setExpenses(await getExpenses()); }
    catch { setExpErr(t('expenses.errLoad')); }
    finally { setExpLoad(false); }
  }, [t]);
  useEffect(() => { loadExpenses(); }, [loadExpenses]);

  const resetForm = () => {
    setAmount(''); setDesc(''); setCounterparty(null);
    setDate(today()); setConf(null);
    setOk(false); setScanErr(''); setScanNote('');
  };

  const handleScanFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) { setScanErr(t('invoiceScan.errEmpty')); return; }
    setScanErr(''); setScanNote(''); setOk(false); setScanning(true);
    try {
      const dto = await scanInvoice(file);
      // Only overwrite what the scan actually found. A field the model missed must not
      // wipe out something the admin already typed, and a missed date must not silently
      // reset the form to today.
      if (dto.amount != null) setAmount(String(dto.amount));
      if (dto.date) setDate(dto.date);
      if (dto.vendor) setDesc(dto.vendor);
      setConf(dto.confidence);
      // A null confidence means the document was analysed but no invoice fields matched —
      // say so, instead of leaving a blank form next to a reassuring badge.
      if (dto.confidence == null) setScanNote(t('invoiceScan.noFields'));
      // Scanning never auto-selects a counterparty — the user always picks it manually.
    } catch { setScanErr(t('invoiceScan.errScan')); }
    finally { setScanning(false); }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setOk(false); setFormErr('');
    const parsed = parseFloat(amount);
    if (!amount || isNaN(parsed) || parsed <= 0) { setFormErr(t('expenses.errAmount')); return; }
    if (!counterparty) { setFormErr(t('finance.errCounterpartyRequired')); return; }
    setSaving(true);
    try {
      await recordExpense({ amountEur: parsed, description: desc, counterpartyId: counterparty.id, expenseDate: date, idempotencyKey: crypto.randomUUID() });
      resetForm(); setOk(true); await loadExpenses();
    } catch { setFormErr(t('expenses.errRecord')); }
    finally { setSaving(false); }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <Card variant="outlined">
        <CardContent>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1.5 }}>{t('finance.addBill')}</Typography>

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, flexWrap: 'wrap', mb: 1.5 }}>
            <Button variant="contained" component="label" size="small" disabled={scanning}>
              {t('finance.scanInvoice')}
              <input data-testid="bill-scan-input" type="file" hidden accept="application/pdf,image/*" onChange={handleScanFile} />
            </Button>
            {scanning && <CircularProgress size={18} />}
            {confidence != null && <Chip data-testid="bill-confidence" size="small" label={`${t('invoiceScan.confidence')}: ${(confidence * 100).toFixed(0)}%`} />}
            <Typography variant="caption" color="text.secondary">{t('finance.orEnterManually')}</Typography>
          </Box>
          {scanErr && <Alert severity="error" sx={{ mb: 1, py: 0 }}>{scanErr}</Alert>}
          {scanNote && <Alert data-testid="bill-scan-note" severity="info" sx={{ mb: 1, py: 0 }}>{scanNote}</Alert>}

          <Box component="form" data-testid="bill-form" onSubmit={handleSubmit} sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
            <TextField label={t('expenses.amountEuro')} type="number" slotProps={{ htmlInput: { step: '0.01', min: '0.01', 'data-testid': 'bill-amount' } }} value={amount} onChange={e => setAmount(e.target.value)} required size="small" />
            <TextField label={t('expenses.expenseDate')} type="date" value={date} onChange={e => setDate(e.target.value)} required size="small" slotProps={{ inputLabel: { shrink: true } }} />
            <TextField label={t('common.description')} value={desc} onChange={e => setDesc(e.target.value)} required size="small" slotProps={{ htmlInput: { 'data-testid': 'bill-desc' } }} />
            <CounterpartyPicker value={counterparty} onChange={setCounterparty} />
            <Box sx={{ gridColumn: '1 / -1', display: 'flex', gap: 1.5, alignItems: 'center' }}>
              <Button data-testid="bill-submit" type="submit" variant="contained" size="small" disabled={saving || !counterparty}>{t('expenses.record')}</Button>
              <Button variant="outlined" size="small" onClick={resetForm} disabled={saving}>{t('finance.clearForm')}</Button>
              {ok && <Alert data-testid="bill-success" severity="success" sx={{ py: 0 }}>{t('expenses.recorded')}</Alert>}
              {formErr && <Alert severity="error" sx={{ py: 0 }}>{formErr}</Alert>}
            </Box>
          </Box>
        </CardContent>
      </Card>

      <Divider><Typography variant="overline" color="text.secondary">{t('nav.expenses')}</Typography></Divider>

      {expLoad ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}><CircularProgress /></Box>
      ) : expErr ? (
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
          <Alert severity="error">{expErr}</Alert>
          <Button variant="outlined" startIcon={<Refresh />} onClick={loadExpenses} size="small">{t('common.retry')}</Button>
        </Box>
      ) : (
        <Box sx={{ overflowX: 'auto' }}>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>{t('common.date')}</TableCell>
                <TableCell>{t('finance.counterpartyLabel')}</TableCell>
                <TableCell>{t('expenses.category')}</TableCell>
                <TableCell>{t('common.description')}</TableCell>
                <TableCell align="right">{t('common.amount')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {expenses.length === 0 ? (
                <TableRow><TableCell colSpan={5} align="center" sx={{ color: 'text.secondary', py: 3 }}>{t('expenses.none')}</TableCell></TableRow>
              ) : expenses.map(e => (
                <TableRow key={e.id} data-testid={`expense-row-${e.id}`}>
                  <TableCell>{e.expenseDate}</TableCell>
                  <TableCell>{e.counterpartyName}</TableCell>
                  <TableCell>{e.counterpartyCategory}</TableCell>
                  <TableCell>{e.description}</TableCell>
                  <TableCell align="right">{formatEur(e.amountEur)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Box>
      )}
    </Box>
  );
}

// ui/angular/src/app/financial/tabs/outcome-tab.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { ExpenseService } from '../../expenses/expense.service';
import { ExpenseListItemDto, ScannedInvoiceDto } from '../../expenses/models';
import { CounterpartyPickerComponent } from '../counterparty-picker.component';
import { Counterparty } from '../../counterparties/counterparty.models';

function today(): string { return new Date().toISOString().slice(0, 10); }
function formatEur(n: number): string { return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(n); }

@Component({
  selector: 'app-outcome-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, CardModule, ButtonModule, ProgressSpinnerModule, TranslatePipe, CounterpartyPickerComponent],
  template: `
    <p-card>
      <ng-template #content>
        <div class="record-form">
          <h3 class="form-title">{{ 'finance.addBill' | translate }}</h3>

          <!-- Scan control -->
          <div class="upload-row">
            <label class="upload-btn">
              {{ 'finance.scanInvoice' | translate }}
              <input
                type="file"
                data-testid="bill-scan-input"
                accept="application/pdf,image/*"
                (change)="onInvoiceSelected($event)"
                style="display:none"
              />
            </label>
          </div>

          @if (scanning()) {
            <div class="center-state">
              <p-progressspinner strokeWidth="4" [style]="{width:'36px',height:'36px'}" />
            </div>
          }

          @if (confidence() !== null) {
            <span class="confidence-chip">
              {{ 'invoiceScan.confidence' | translate }}: {{ (confidence()! * 100).toFixed(0) }}%
            </span>
          }

          @if (scanNote()) {
            <p class="scan-note" data-testid="bill-scan-note">{{ scanNote() }}</p>
          }

          <p class="scan-caption">{{ 'finance.orEnterManually' | translate }}</p>

          @if (scanErr()) {
            <p class="error-msg">{{ scanErr() }}</p>
          }

          <!-- Shared bill form -->
          <form data-testid="bill-form" (ngSubmit)="onSubmit()">
            <div class="form-grid">
              <div class="form-row">
                <label>{{ 'expenses.amountEuro' | translate }}</label>
                <input
                  type="number"
                  step="0.01"
                  min="0.01"
                  data-testid="bill-amount"
                  name="billAmt"
                  [(ngModel)]="billForm.amountEurStr"
                  class="form-input"
                />
              </div>
              <div class="form-row">
                <label>{{ 'expenses.expenseDate' | translate }}</label>
                <input
                  type="date"
                  name="billDate"
                  [(ngModel)]="billForm.expenseDate"
                  class="form-input"
                />
              </div>
              <div class="form-row">
                <label>{{ 'common.description' | translate }}</label>
                <input
                  type="text"
                  data-testid="bill-desc"
                  name="billDesc"
                  [(ngModel)]="billForm.description"
                  class="form-input"
                />
              </div>
              <div class="form-row">
                <label>{{ 'finance.counterpartyLabel' | translate }}</label>
                <app-counterparty-picker data-testid="bill-counterparty" (counterpartyChange)="onCounterpartyChange($event)" />
              </div>
            </div>
            <div class="scan-actions">
              <button type="submit" data-testid="bill-submit" class="submit-btn" [disabled]="saving()">
                {{ 'expenses.record' | translate }}
              </button>
              <button type="button" class="reset-btn" (click)="resetForm()">
                {{ 'finance.clearForm' | translate }}
              </button>
            </div>
            @if (ok()) {
              <p data-testid="bill-success" class="success-msg">{{ 'expenses.recorded' | translate }}</p>
            }
            @if (formErr()) {
              <p class="error-msg">{{ formErr() }}</p>
            }
          </form>
        </div>

        <!-- Expenses list -->
        <div class="section-divider"><span class="section-label">{{ 'nav.expenses' | translate }}</span></div>

        @if (expLoading()) {
          <div class="center-state"><p-progressspinner strokeWidth="4" [style]="{width:'36px',height:'36px'}" /></div>
        } @else if (expError()) {
          <div class="error-state">
            <p>{{ expError() }}</p>
            <button (click)="loadExpenses()">{{ 'common.retry' | translate }}</button>
          </div>
        } @else {
          <div class="table-scroll">
            <table class="fin-table">
              <thead><tr>
                <th>{{ 'common.date' | translate }}</th>
                <th>{{ 'expenses.category' | translate }}</th>
                <th>{{ 'common.description' | translate }}</th>
                <th>{{ 'common.amount' | translate }}</th>
              </tr></thead>
              <tbody>
                @for (e of expenses(); track e.id) {
                  <tr [attr.data-testid]="'expense-row-' + e.id">
                    <td>{{ e.expenseDate }}</td>
                    <td>{{ e.counterpartyName }} ({{ e.counterpartyCategory }})</td>
                    <td>{{ e.description }}</td>
                    <td>{{ formatEur(e.amountEur) }}</td>
                  </tr>
                }
                @if (expenses().length === 0) {
                  <tr><td colspan="4" class="empty-cell">{{ 'expenses.none' | translate }}</td></tr>
                }
              </tbody>
            </table>
          </div>
        }
      </ng-template>
    </p-card>
  `,
  styles: [`
    .record-form { background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
    .form-title { margin: 0 0 12px; font-size: .9375rem; font-weight: 600; }
    .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
    @media (max-width: 480px) { .form-grid { grid-template-columns: 1fr; } }
    .form-row { display: flex; flex-direction: column; gap: 4px; }
    .form-row label { font-size: .8125rem; font-weight: 500; color: #555; }
    .form-input { padding: 7px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: .875rem; }
    .submit-btn { background: #2e6b4f; color: white; border: none; padding: 7px 18px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .submit-btn:hover { background: #245a40; }
    .submit-btn:disabled { opacity: .6; cursor: not-allowed; }
    .reset-btn { background: transparent; border: 1px solid #ccc; color: #555; padding: 7px 16px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .reset-btn:hover { background: #f5f5f0; }
    .success-msg { color: #2e6b4f; font-weight: 500; margin: 8px 0 0; font-size: .875rem; }
    .error-msg { color: #c00; margin: 8px 0 0; font-size: .875rem; }
    .table-scroll { overflow-x: auto; }
    .fin-table { width: 100%; border-collapse: collapse; }
    .fin-table th, .fin-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: .875rem; white-space: nowrap; }
    .fin-table th { background: #f9f9f7; font-weight: 600; color: #555; }
    .empty-cell { text-align: center; color: #999; padding: 16px; white-space: normal; }
    .center-state { display: flex; justify-content: center; padding: 32px; }
    .error-state { display: flex; flex-direction: column; align-items: center; gap: 12px; padding: 32px; color: #c00; }
    .upload-row { margin-bottom: 8px; }
    .upload-btn { display: inline-block; background: #2e6b4f; color: white; padding: 7px 18px; border-radius: 6px; cursor: pointer; font-size: .875rem; }
    .upload-btn:hover { background: #245a40; }
    .confidence-chip { display: inline-block; background: #e8f0ec; color: #2e6b4f; border-radius: 12px; padding: 2px 10px; font-size: .8125rem; font-weight: 600; margin-bottom: 8px; }
    .scan-note { background: #fdf6e3; color: #8a6d3b; border-radius: 6px; padding: 6px 10px; font-size: .8125rem; margin: 0 0 8px; }
    .scan-caption { font-size: .8125rem; color: #888; margin: 6px 0 8px; }
    .scan-actions { display: flex; gap: 12px; align-items: center; margin-top: 4px; }
    .confidence-val { background: none; border: none; padding-left: 0; font-size: .875rem; color: #555; }
    .section-divider { display: flex; align-items: center; margin: 24px 0 16px; gap: 12px; }
    .section-divider::before, .section-divider::after { content: ''; flex: 1; height: 1px; background: #e0e0e0; }
    .section-label { font-size: .75rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #888; white-space: nowrap; }
  `],
})
export class OutcomeTabComponent implements OnInit {
  private readonly expSvc = inject(ExpenseService);
  private readonly t = inject(TranslateService);

  readonly formatEur = formatEur;

  billForm = { amountEurStr: '', expenseDate: today(), description: '' };
  selectedCounterparty: Counterparty | null = null;
  readonly confidence = signal<number | null>(null);
  readonly scanning = signal(false);
  readonly scanErr = signal<string | null>(null);
  readonly scanNote = signal<string | null>(null);
  readonly saving = signal(false);
  readonly ok = signal(false);
  readonly formErr = signal<string | null>(null);

  readonly expenses = signal<ExpenseListItemDto[]>([]);
  readonly expLoading = signal(true);
  readonly expError = signal<string | null>(null);

  ngOnInit(): void { this.loadExpenses(); }

  loadExpenses(): void {
    this.expLoading.set(true); this.expError.set(null);
    this.expSvc.getExpenses().subscribe({
      next: list => { this.expenses.set(list); this.expLoading.set(false); },
      error: () => { this.expError.set(this.t.instant('expenses.errLoad')); this.expLoading.set(false); },
    });
  }

  resetForm(): void {
    this.billForm = { amountEurStr: '', expenseDate: today(), description: '' };
    this.selectedCounterparty = null;
    this.confidence.set(null); this.ok.set(false); this.scanErr.set(null); this.scanNote.set(null);
  }

  onCounterpartyChange(counterparty: Counterparty | null): void {
    this.selectedCounterparty = counterparty;
  }

  onInvoiceSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    input.value = '';
    if (!file) { this.scanErr.set(this.t.instant('invoiceScan.errEmpty')); return; }
    this.scanErr.set(null); this.scanNote.set(null); this.ok.set(false); this.scanning.set(true);
    this.expSvc.scanInvoice(file).subscribe({
      next: (dto: ScannedInvoiceDto) => {
        // Only overwrite what the scan actually found. A field the model missed must not
        // wipe out something the admin already typed, and a missed date must not silently
        // reset the form to today.
        if (dto.amount != null) this.billForm.amountEurStr = String(dto.amount);
        if (dto.date) this.billForm.expenseDate = dto.date;
        if (dto.vendor) this.billForm.description = dto.vendor;
        // Scanning never auto-selects a counterparty — manual selection is always required.
        this.confidence.set(dto.confidence);
        // A null confidence means the document was analysed but no invoice fields matched —
        // say so, instead of leaving a blank form next to a reassuring badge.
        this.scanNote.set(dto.confidence == null ? this.t.instant('invoiceScan.noFields') : null);
        this.scanning.set(false);
      },
      error: () => { this.scanErr.set(this.t.instant('invoiceScan.errScan')); this.scanning.set(false); },
    });
  }

  onSubmit(): void {
    this.ok.set(false); this.formErr.set(null);
    if (!this.selectedCounterparty) { this.formErr.set(this.t.instant('finance.errCounterpartyRequired')); return; }
    const parsed = parseFloat(this.billForm.amountEurStr);
    if (!this.billForm.amountEurStr || isNaN(parsed) || parsed <= 0) { this.formErr.set(this.t.instant('expenses.errAmount')); return; }
    this.saving.set(true);
    this.expSvc.recordExpense({
      amountEur: parsed, description: this.billForm.description,
      counterpartyId: this.selectedCounterparty.id,
      expenseDate: this.billForm.expenseDate, idempotencyKey: crypto.randomUUID(),
    }).subscribe({
      next: () => { this.resetForm(); this.ok.set(true); this.saving.set(false); this.loadExpenses(); },
      error: () => { this.formErr.set(this.t.instant('expenses.errRecord')); this.saving.set(false); },
    });
  }
}
