// ui/angular/src/app/directory/directory-list.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import { TableModule, SortIcon } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { ToggleSwitchModule } from 'primeng/toggleswitch';
import { ToastModule } from 'primeng/toast';
import { TagModule } from 'primeng/tag';
import { CardModule } from 'primeng/card';
import { SelectButton } from 'primeng/selectbutton';
import { MessageService } from 'primeng/api';

import { DirectoryService } from './directory.service';
import { AdminContact, DirectoryEntry, DirectoryEntryAdmin, MyContact } from './models';
import { RoleService } from '../role.service';

@Component({
  selector: 'app-directory-list',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    TableModule,
    SortIcon,
    ButtonModule,
    DialogModule,
    InputTextModule,
    ToggleSwitchModule,
    ToastModule,
    TagModule,
    CardModule,
    SelectButton,
  ],
  providers: [MessageService],
  template: `
    <p-toast />

    <div class="harmonia-shell">
      <header class="harmonia-header">
        <span class="harmonia-logo">🏡 Harmonia</span>
        <span class="harmonia-subtitle">Resident Portal</span>
        <div class="flex-spacer"></div>
        <a routerLink="/directory" class="nav-link nav-active">Directory</a>
        <a routerLink="/reservations" class="nav-link">Reservations</a>
        <a routerLink="/financial" class="nav-link">Finance</a>
        <a routerLink="/expenses" class="nav-link">Expenses</a>
        <a routerLink="/maintenance-fees" class="nav-link">Fees</a>
        <a routerLink="/payments" class="nav-link">Payments</a>
        <a routerLink="/notifications" class="nav-link">Notifications</a>
        <a routerLink="/privacy" class="nav-link">Privacy</a>
        <a routerLink="/contact-edit" class="nav-link">Edit Contact</a>
        @if (isAdmin) { <a routerLink="/admin-pending" class="nav-link">Pending Users</a> }
        @if (isAdmin) {
        <span class="role-label">View as:</span>
        <p-selectbutton
          [options]="roleOptions"
          [ngModel]="selectedRole"
          (ngModelChange)="onRoleChange($event)"
          optionLabel="label"
          optionValue="value"
          styleClass="role-toggle"
        />
        }
      </header>

      <main class="harmonia-content" [class.wide]="selectedRole === 'admin'">
        <p-card>
          <ng-template #title>
            <div class="card-title-row">
              <span>Member Directory</span>
              @if (selectedRole === 'resident') {
                <p-button
                  label="My Profile"
                  icon="pi pi-user-edit"
                  (onClick)="openEditDialog()"
                  [rounded]="true"
                  severity="secondary"
                />
              }
            </div>
          </ng-template>

          <ng-template #subtitle>
            @if (selectedRole === 'resident') {
              Showing residents who have shared their details.
            } @else {
              Admin view — all active residents including opted-out.
            }
          </ng-template>

          @if (loading()) {
            <div class="loading-row">
              <i class="pi pi-spin pi-spinner" style="font-size:1.5rem"></i>
              <span>Loading directory…</span>
            </div>
          } @else if (error()) {
            <div class="error-row">
              <i class="pi pi-exclamation-circle"></i>
              <span>{{ error() }}</span>
              <p-button label="Retry" icon="pi pi-refresh" severity="secondary" (onClick)="load()" />
            </div>
          } @else if (selectedRole === 'resident') {

            <!-- ── Resident table ── -->
            <p-table
              [value]="entries()"
              [paginator]="true"
              [rows]="10"
              [rowsPerPageOptions]="[10, 25, 50]"
              [globalFilterFields]="['displayName', 'householdRef']"
              styleClass="p-datatable-striped p-datatable-sm"
              #dt
            >
              <ng-template #caption>
                <div class="table-caption">
                  <span>{{ entries().length }} resident(s)</span>
                  <span class="p-input-icon-left">
                    <i class="pi pi-search"></i>
                    <input
                      pInputText type="text" placeholder="Search…"
                      (input)="dt.filterGlobal($any($event.target).value, 'contains')"
                    />
                  </span>
                </div>
              </ng-template>

              <ng-template #header>
                <tr>
                  <th pSortableColumn="householdRef" style="width:12rem">
                    Apartment <p-sort-icon field="householdRef" />
                  </th>
                  <th pSortableColumn="displayName">
                    Name <p-sort-icon field="displayName" />
                  </th>
                </tr>
              </ng-template>

              <ng-template #body let-entry>
                <tr>
                  <td><p-tag [value]="entry.householdRef" severity="secondary" /></td>
                  <td>{{ entry.displayName ?? '—' }}</td>
                </tr>
              </ng-template>

              <ng-template #emptymessage>
                <tr><td colspan="2" class="empty-message">No residents found.</td></tr>
              </ng-template>
            </p-table>

          } @else {

            <!-- ── Admin table ── -->
            <p-table
              [value]="adminEntries()"
              [paginator]="true"
              [rows]="25"
              [rowsPerPageOptions]="[25, 50, 100]"
              [globalFilterFields]="['displayName', 'householdRef', 'phone', 'email']"
              styleClass="p-datatable-striped p-datatable-sm"
              #adminDt
            >
              <ng-template #caption>
                <div class="table-caption">
                  <span>{{ adminEntries().length }} resident(s)</span>
                  <span class="p-input-icon-left">
                    <i class="pi pi-search"></i>
                    <input
                      pInputText type="text"
                      placeholder="Search name, apartment, phone, email…"
                      (input)="adminDt.filterGlobal($any($event.target).value, 'contains')"
                    />
                  </span>
                </div>
              </ng-template>

              <ng-template #header>
                <tr>
                  <th pSortableColumn="householdRef" style="width:10rem">
                    Apartment <p-sort-icon field="householdRef" />
                  </th>
                  <th pSortableColumn="displayName" style="width:14rem">
                    Name <p-sort-icon field="displayName" />
                  </th>
                  <th pSortableColumn="phone" style="width:12rem">
                    Phone <p-sort-icon field="phone" />
                  </th>
                  <th pSortableColumn="email" style="width:16rem">
                    Email <p-sort-icon field="email" />
                  </th>
                  <th style="width:9rem">Opt-out</th>
                  <th pSortableColumn="deactivatedAt" style="width:12rem">
                    Departed <p-sort-icon field="deactivatedAt" />
                  </th>
                  <th style="width:9rem"></th>
                </tr>
              </ng-template>

              <ng-template #body let-entry>
                <tr>
                  <td><p-tag [value]="entry.householdRef" severity="secondary" /></td>
                  <td>{{ entry.displayName ?? '—' }}</td>
                  <td>{{ entry.phone ?? '—' }}</td>
                  <td>{{ entry.email ?? '—' }}</td>
                  <td>
                    @if (entry.isOptedOut) {
                      <p-tag value="Opted out" severity="warn" />
                    } @else {
                      <p-tag value="Active" severity="success" />
                    }
                  </td>
                  <td>{{ entry.deactivatedAt ? (entry.deactivatedAt | date:'MMM d, y') : '—' }}</td>
                  <td>
                    <div class="action-cell">
                      <p-button
                        icon="pi pi-pencil"
                        [rounded]="true" [text]="true"
                        severity="secondary" size="small"
                        (onClick)="openAdminEdit(entry)"
                      />
                      <p-button
                        icon="pi pi-user-minus"
                        [rounded]="true" [text]="true"
                        severity="danger" size="small"
                        (onClick)="openDepartConfirm(entry.householdRef)"
                      />
                      <p-button
                        icon="pi pi-trash"
                        [rounded]="true" [text]="true"
                        severity="danger" size="small"
                        title="Erase contact data"
                        (onClick)="openEraseContact(entry.householdRef)"
                      />
                    </div>
                  </td>
                </tr>
              </ng-template>

              <ng-template #emptymessage>
                <tr><td colspan="7" class="empty-message">No residents found.</td></tr>
              </ng-template>
            </p-table>

          }
        </p-card>
      </main>
    </div>

    <!-- ── Resident edit dialog ── -->
    <p-dialog
      [(visible)]="editVisible"
      header="My Profile"
      [modal]="true" [style]="{ width: '32rem' }"
      [draggable]="false" [resizable]="false"
    >
      <div class="edit-form">
        <div class="field">
          <label for="displayName">Display Name</label>
          <input id="displayName" pInputText [(ngModel)]="form.displayName"
            placeholder="Your name as shown to neighbours" class="w-full" />
        </div>
        <div class="field">
          <label for="phone">Phone</label>
          <input id="phone" pInputText [(ngModel)]="form.phone"
            placeholder="+359 88 …" class="w-full" />
        </div>
        <div class="field">
          <label for="email">Email</label>
          <input id="email" pInputText type="email" [(ngModel)]="form.email"
            placeholder="you@example.com" class="w-full" />
        </div>
        <div class="field opt-out-field">
          <div class="opt-out-row">
            <div>
              <span class="opt-out-label">Hide me from the directory</span>
              <p class="opt-out-hint">
                When enabled, your name will not appear to other residents.
              </p>
            </div>
            <p-toggleswitch [(ngModel)]="form.isOptedOut" />
          </div>
        </div>
      </div>
      <ng-template #footer>
        <p-button label="Delete my data" icon="pi pi-trash" severity="danger"
          [outlined]="true" (onClick)="openEraseMyContact()" [style]="{'margin-right': 'auto'}" />
        <p-button label="Cancel" icon="pi pi-times" severity="secondary"
          [outlined]="true" (onClick)="editVisible = false" />
        <p-button label="Save" icon="pi pi-check"
          [loading]="saving()" (onClick)="save()" />
      </ng-template>
    </p-dialog>

    <!-- ── Admin edit dialog ── -->
    <p-dialog
      [(visible)]="adminEditVisible"
      [header]="'Edit Resident — ' + selectedAdminRef"
      [modal]="true" [style]="{ width: '36rem' }"
      [draggable]="false" [resizable]="false"
    >
      <div class="edit-form">
        <div class="field">
          <label>Display Name</label>
          <input pInputText [(ngModel)]="adminForm.displayName" class="w-full" />
        </div>
        <div class="field">
          <label>Phone</label>
          <input pInputText [(ngModel)]="adminForm.phone" class="w-full" />
        </div>
        <div class="field">
          <label>Email</label>
          <input pInputText type="email" [(ngModel)]="adminForm.email" class="w-full" />
        </div>
        <div class="field">
          <label>Notes</label>
          <textarea
            [(ngModel)]="adminForm.notes"
            rows="4"
            placeholder="Internal notes — not visible to resident"
            class="admin-notes"
          ></textarea>
        </div>
        <div class="field opt-out-field">
          <div class="opt-out-row">
            <span class="opt-out-label">Opted out of directory</span>
            <p-toggleswitch [(ngModel)]="adminForm.isOptedOut" />
          </div>
        </div>
      </div>
      <ng-template #footer>
        <p-button label="Cancel" icon="pi pi-times" severity="secondary"
          [outlined]="true" (onClick)="adminEditVisible = false" />
        <p-button label="Save" icon="pi pi-check"
          [loading]="adminSaving()" (onClick)="saveAdminEdit()" />
      </ng-template>
    </p-dialog>

    <!-- ── Mark Departed confirm dialog ── -->
    <p-dialog
      [(visible)]="departVisible"
      header="Mark as Departed?"
      [modal]="true" [style]="{ width: '28rem' }"
      [draggable]="false" [resizable]="false"
      [closable]="!departing()"
    >
      <p class="depart-message">
        Apartment <strong>{{ departRef }}</strong> will be removed from the
        active directory. This cannot be undone from this screen.
      </p>
      <ng-template #footer>
        <p-button
          label="Cancel" icon="pi pi-times"
          severity="secondary" [outlined]="true"
          [disabled]="departing()"
          (onClick)="departVisible = false"
        />
        <p-button
          label="Mark Departed" icon="pi pi-user-minus"
          severity="danger"
          [loading]="departing()"
          (onClick)="confirmDepart()"
        />
      </ng-template>
    </p-dialog>

    <!-- ── Erase my contact dialog ── -->
    <p-dialog
      [(visible)]="eraseMyVisible"
      header="Delete my data?"
      [modal]="true" [style]="{ width: '28rem' }"
      [draggable]="false" [resizable]="false"
      [closable]="!erasing()"
    >
      <p class="depart-message">
        All your contact information will be <strong>permanently deleted</strong>.
        This cannot be undone.
      </p>
      <ng-template #footer>
        <p-button
          label="Cancel" icon="pi pi-times"
          severity="secondary" [outlined]="true"
          [disabled]="erasing()"
          (onClick)="eraseMyVisible = false"
        />
        <p-button
          label="Delete my data" icon="pi pi-trash"
          severity="danger"
          [loading]="erasing()"
          (onClick)="confirmEraseMyContact()"
        />
      </ng-template>
    </p-dialog>

    <!-- ── Erase contact dialog (admin) ── -->
    <p-dialog
      [(visible)]="eraseContactVisible"
      header="Erase contact data?"
      [modal]="true" [style]="{ width: '28rem' }"
      [draggable]="false" [resizable]="false"
      [closable]="!erasingContact()"
    >
      <p class="depart-message">
        All data for apartment <strong>{{ eraseContactRef }}</strong> will be
        <strong>permanently deleted</strong>. This cannot be undone.
      </p>
      <ng-template #footer>
        <p-button
          label="Cancel" icon="pi pi-times"
          severity="secondary" [outlined]="true"
          [disabled]="erasingContact()"
          (onClick)="eraseContactVisible = false"
        />
        <p-button
          label="Erase contact" icon="pi pi-trash"
          severity="danger"
          [loading]="erasingContact()"
          (onClick)="confirmEraseContact()"
        />
      </ng-template>
    </p-dialog>
  `,
  styles: [`
    .harmonia-shell { min-height: 100vh; background: var(--p-surface-ground); }

    .harmonia-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.75rem 2rem;
      background: var(--p-primary-color);
      color: var(--p-primary-contrast-color);
      box-shadow: 0 2px 8px rgba(0,0,0,.15);
    }

    .harmonia-logo   { font-size: 1.25rem; font-weight: 700; letter-spacing: -.5px; }
    .harmonia-subtitle { font-size: 0.875rem; opacity: .8; }
    .flex-spacer     { flex: 1; }
    .nav-link { color: rgba(255,255,255,.75); text-decoration: none; padding: 6px 12px; border-radius: 6px; font-size: .875rem; }
    .nav-link:hover { background: rgba(255,255,255,.1); }
    .nav-active { background: rgba(255,255,255,.22); color: white; font-weight: 600; }
    .role-label      { font-size: 0.8125rem; opacity: 0.75; white-space: nowrap; }

    ::ng-deep .role-toggle .p-selectbutton { border: 1px solid rgba(255,255,255,0.35); border-radius: 6px; overflow: hidden; }
    ::ng-deep .role-toggle .p-togglebutton { background: transparent !important; color: rgba(255,255,255,0.8) !important; border: none !important; padding: 0.375rem 1rem; font-size: 0.8125rem; }
    ::ng-deep .role-toggle .p-togglebutton.p-highlight { background: rgba(255,255,255,0.22) !important; color: white !important; font-weight: 600; }

    .harmonia-content { max-width: 900px; margin: 2rem auto; padding: 0 1rem; transition: max-width 0.2s; }
    .harmonia-content.wide { max-width: 1200px; }

    .card-title-row { display: flex; align-items: center; justify-content: space-between; }
    .table-caption  { display: flex; align-items: center; justify-content: space-between; gap: 1rem; }

    .loading-row, .error-row {
      display: flex; align-items: center; gap: 0.75rem;
      padding: 2rem; color: var(--p-text-muted-color);
    }
    .error-row { color: var(--p-red-500, #ef4444); }
    .empty-message { text-align: center; padding: 2rem; color: var(--p-text-muted-color); }

    .action-cell    { display: flex; gap: 0.125rem; }

    .edit-form      { display: flex; flex-direction: column; gap: 1.25rem; padding-top: 0.5rem; }
    .field          { display: flex; flex-direction: column; gap: 0.375rem; }
    .field label    { font-size: 0.875rem; font-weight: 500; color: var(--p-text-color); }
    .field input, .field textarea { width: 100%; }

    .admin-notes {
      font-family: inherit;
      font-size: 0.875rem;
      padding: 0.5rem 0.75rem;
      border: 1px solid var(--p-inputtext-border-color, #cbd5e1);
      border-radius: 6px;
      color: var(--p-text-color);
      background: var(--p-inputtext-background, #fff);
      resize: vertical;
      line-height: 1.5;
    }
    .admin-notes:focus { outline: 2px solid var(--p-primary-color); outline-offset: -1px; }

    .opt-out-field  { border-top: 1px solid var(--p-surface-border); padding-top: 1.25rem; }
    .opt-out-row    { display: flex; align-items: center; justify-content: space-between; gap: 1rem; }
    .opt-out-label  { font-size: 0.875rem; font-weight: 500; }
    .opt-out-hint   { font-size: 0.8rem; color: var(--p-text-muted-color); margin: 0.25rem 0 0; }

    .depart-message { margin: 0; line-height: 1.6; color: var(--p-text-color); }

    .w-full { width: 100%; }
  `],
})
export class DirectoryListComponent implements OnInit {
  private readonly svc = inject(DirectoryService);
  private readonly msg = inject(MessageService);
  readonly isAdmin = inject(RoleService).isAdmin;

  // ── shared ──
  loading = signal(false);
  error   = signal<string | null>(null);

  // ── role ──
  selectedRole: 'resident' | 'admin' = 'resident';
  roleOptions = [
    { label: 'Resident', value: 'resident' },
    { label: 'Admin',    value: 'admin'    },
  ];

  onRoleChange(role: 'resident' | 'admin') {
    this.selectedRole = role;
    this.load();
  }

  // ── resident ──
  entries     = signal<DirectoryEntry[]>([]);
  editVisible = false;
  saving      = signal(false);
  form: MyContact = { displayName: '', phone: '', email: '', isOptedOut: false };

  // ── admin ──
  adminEntries     = signal<DirectoryEntryAdmin[]>([]);
  adminEditVisible = false;
  adminSaving      = signal(false);
  selectedAdminRef = '';
  adminForm: AdminContact = { displayName: '', phone: '', email: '', notes: '', isOptedOut: false };

  // ── depart ──
  departVisible = false;
  departRef     = '';
  departing     = signal(false);

  // ── erase my contact ──
  eraseMyVisible = false;
  erasing        = signal(false);

  // ── erase contact (admin) ──
  eraseContactVisible = false;
  eraseContactRef     = '';
  erasingContact      = signal(false);

  ngOnInit() { this.load(); }

  load() {
    this.loading.set(true);
    this.error.set(null);
    if (this.selectedRole === 'resident') {
      this.svc.getDirectory().subscribe({
        next: e  => { this.entries.set(e);      this.loading.set(false); },
        error: () => { this.error.set(API_ERROR); this.loading.set(false); },
      });
    } else {
      this.svc.getAdminDirectory().subscribe({
        next: e  => { this.adminEntries.set(e); this.loading.set(false); },
        error: () => { this.error.set(API_ERROR); this.loading.set(false); },
      });
    }
  }

  // ── resident handlers ──
  openEditDialog() {
    this.form = { displayName: '', phone: '', email: '', isOptedOut: false };
    this.editVisible = true;
  }

  save() {
    this.saving.set(true);
    this.svc.updateMyContact({
      displayName: this.form.displayName || null,
      phone:       this.form.phone       || null,
      email:       this.form.email       || null,
      isOptedOut:  this.form.isOptedOut,
    }).subscribe({
      next: () => {
        this.saving.set(false);
        this.editVisible = false;
        this.msg.add({ severity: 'success', summary: 'Saved', detail: 'Your profile has been updated.' });
        this.load();
      },
      error: () => {
        this.saving.set(false);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Could not save. Please try again.' });
      },
    });
  }

  // ── admin handlers ──
  openAdminEdit(entry: DirectoryEntryAdmin) {
    this.selectedAdminRef = entry.householdRef;
    this.adminForm = {
      displayName: entry.displayName ?? '',
      phone:       entry.phone       ?? '',
      email:       entry.email       ?? '',
      notes:       entry.notes       ?? '',
      isOptedOut:  entry.isOptedOut,
    };
    this.adminEditVisible = true;
  }

  saveAdminEdit() {
    this.adminSaving.set(true);
    this.svc.adminUpdateContact(this.selectedAdminRef, {
      displayName: this.adminForm.displayName || null,
      phone:       this.adminForm.phone       || null,
      email:       this.adminForm.email       || null,
      notes:       this.adminForm.notes       || null,
      isOptedOut:  this.adminForm.isOptedOut,
    }).subscribe({
      next: () => {
        this.adminSaving.set(false);
        this.adminEditVisible = false;
        this.msg.add({ severity: 'success', summary: 'Saved', detail: 'Resident updated.' });
        this.load();
      },
      error: () => {
        this.adminSaving.set(false);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Could not save. Please try again.' });
      },
    });
  }

  // ── depart handlers ──
  openDepartConfirm(householdRef: string) {
    this.departRef     = householdRef;
    this.departVisible = true;
  }

  confirmDepart() {
    this.departing.set(true);
    this.svc.markDeparted(this.departRef).subscribe({
      next: () => {
        this.departing.set(false);
        this.departVisible = false;
        this.adminEntries.update(list => list.filter(e => e.householdRef !== this.departRef));
        this.msg.add({
          severity: 'success',
          summary: 'Departed',
          detail: `${this.departRef} marked as departed.`,
        });
      },
      error: () => {
        this.departing.set(false);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Could not mark as departed.' });
      },
    });
  }

  // ── erase my contact handlers ──
  openEraseMyContact() {
    this.editVisible    = false;
    this.eraseMyVisible = true;
  }

  confirmEraseMyContact() {
    this.erasing.set(true);
    this.svc.eraseMyContact().subscribe({
      next: () => {
        this.erasing.set(false);
        this.eraseMyVisible = false;
        this.entries.set([]);
        this.msg.add({ severity: 'success', summary: 'Deleted', detail: 'Your data has been permanently deleted.' });
      },
      error: () => {
        this.erasing.set(false);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Could not delete your data.' });
      },
    });
  }

  // ── erase contact handlers (admin) ──
  openEraseContact(householdRef: string) {
    this.eraseContactRef     = householdRef;
    this.eraseContactVisible = true;
  }

  confirmEraseContact() {
    this.erasingContact.set(true);
    this.svc.eraseContact(this.eraseContactRef).subscribe({
      next: () => {
        this.erasingContact.set(false);
        this.eraseContactVisible = false;
        this.adminEntries.update(list => list.filter(e => e.householdRef !== this.eraseContactRef));
        this.msg.add({ severity: 'success', summary: 'Erased', detail: `Data for ${this.eraseContactRef} permanently deleted.` });
      },
      error: () => {
        this.erasingContact.set(false);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Could not erase contact data.' });
      },
    });
  }
}

const API_ERROR = 'Could not reach the Harmonia API. Is it running on port 5000?';

// ui/react/src/components/DirectoryList.tsx
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Chip,
  CircularProgress,
  IconButton,
  InputAdornment,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TextField,
  Typography,
} from '@mui/material';
import EditIcon from '@mui/icons-material/EditOutlined';
import PersonOffIcon from '@mui/icons-material/PersonOffOutlined';
import ManageAccountsIcon from '@mui/icons-material/ManageAccountsOutlined';
import RefreshIcon from '@mui/icons-material/Refresh';
import SearchIcon from '@mui/icons-material/Search';
import {
  adminUpdateContact,
  getAdminDirectory,
  getDirectory,
  markDeparted,
  updateMyContact,
} from '../api/directory';
import {
  AdminContact,
  DirectoryEntry,
  DirectoryEntryAdmin,
  MyContact,
  Role,
} from '../types';
import AdminEditDialog from './AdminEditDialog';
import EditContactDialog from './EditContactDialog';
import MarkDepartedDialog from './MarkDepartedDialog';
import DeleteForeverIcon from '@mui/icons-material/DeleteForeverOutlined';
import { eraseMyContact, eraseContact } from '../api/privacy';
import EraseMyContactDialog from './EraseMyContactDialog';
import EraseContactDialog from './EraseContactDialog';

const BLANK_RESIDENT: MyContact = { displayName: '', phone: '', email: '', isOptedOut: false };
const BLANK_ADMIN: AdminContact = { displayName: '', phone: '', email: '', notes: '', isOptedOut: false };

interface Props { role: Role; }

const DirectoryList: React.FC<Props> = ({ role }) => {
  // resident
  const [rows, setRows]                   = useState<DirectoryEntry[]>([]);
  const [residentDialogOpen, setResidentDialogOpen] = useState(false);
  const [residentForm, setResidentForm]   = useState<MyContact>(BLANK_RESIDENT);
  const [saving, setSaving]               = useState(false);

  // admin
  const [adminRows, setAdminRows]         = useState<DirectoryEntryAdmin[]>([]);
  const [adminEditOpen, setAdminEditOpen] = useState(false);
  const [adminRef, setAdminRef]           = useState('');
  const [adminForm, setAdminForm]         = useState<AdminContact>(BLANK_ADMIN);
  const [adminSaving, setAdminSaving]     = useState(false);

  // depart
  const [departOpen, setDepartOpen]       = useState(false);
  const [departRef, setDepartRef]         = useState('');
  const [departing, setDeparting]         = useState(false);

  // erase my contact
  const [eraseMyOpen, setEraseMyOpen]           = useState(false);
  const [erasingMy, setErasingMy]               = useState(false);
  // erase contact (admin)
  const [eraseContactOpen, setEraseContactOpen] = useState(false);
  const [eraseContactRef, setEraseContactRef]   = useState('');
  const [erasingContact, setErasingContact]     = useState(false);

  // shared
  const [loading, setLoading]             = useState(false);
  const [error, setError]                 = useState<string>('');
  const [search, setSearch]               = useState('');
  const [toast, setToast]                 = useState<string>('');

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 4000); };

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      if (role === 'resident') {
        setRows(await getDirectory());
      } else {
        setAdminRows(await getAdminDirectory());
      }
    } catch {
      setError('Could not reach the Harmonia API. Is it running on port 5000?');
    } finally {
      setLoading(false);
    }
  }, [role]);

  useEffect(() => { load(); }, [load]);

  // ── resident handlers ──────────────────────────────────────────────────────
  const handleResidentSave = async () => {
    setSaving(true);
    try {
      await updateMyContact({
        displayName: residentForm.displayName || null,
        phone:       residentForm.phone       || null,
        email:       residentForm.email       || null,
        isOptedOut:  residentForm.isOptedOut,
      });
      setResidentDialogOpen(false);
      showToast('Profile updated.');
      await load();
    } catch {
      setError('Could not save. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  // ── admin handlers ─────────────────────────────────────────────────────────
  const openAdminEdit = useCallback((entry: DirectoryEntryAdmin) => {
    setAdminRef(entry.householdRef);
    setAdminForm({
      displayName: entry.displayName ?? '',
      phone:       entry.phone       ?? '',
      email:       entry.email       ?? '',
      notes:       entry.notes       ?? '',
      isOptedOut:  entry.isOptedOut,
    });
    setAdminEditOpen(true);
  }, []);

  const handleAdminSave = async () => {
    setAdminSaving(true);
    try {
      await adminUpdateContact(adminRef, {
        displayName: adminForm.displayName || null,
        phone:       adminForm.phone       || null,
        email:       adminForm.email       || null,
        notes:       adminForm.notes       || null,
        isOptedOut:  adminForm.isOptedOut,
      });
      setAdminEditOpen(false);
      showToast('Resident updated.');
      await load();
    } catch {
      setError('Could not save. Please try again.');
    } finally {
      setAdminSaving(false);
    }
  };

  const openDepart = useCallback((householdRef: string) => {
    setDepartRef(householdRef);
    setDepartOpen(true);
  }, []);

  const handleDepart = async () => {
    setDeparting(true);
    try {
      await markDeparted(departRef);
      setAdminRows(prev => prev.filter(r => r.householdRef !== departRef));
      setDepartOpen(false);
      showToast(`${departRef} marked as departed.`);
    } catch {
      setError('Could not mark as departed. Please try again.');
    } finally {
      setDeparting(false);
    }
  };

  const handleEraseMyContact = async () => {
    setErasingMy(true);
    try {
      await eraseMyContact();
      setEraseMyOpen(false);
      setResidentDialogOpen(false);
      setRows([]);
      showToast('Your data has been permanently deleted.');
    } catch {
      setError('Could not delete your data. Please try again.');
    } finally {
      setErasingMy(false);
    }
  };

  const handleEraseContact = async () => {
    setErasingContact(true);
    try {
      await eraseContact(eraseContactRef);
      setAdminRows(prev => prev.filter(r => r.householdRef !== eraseContactRef));
      setEraseContactOpen(false);
      showToast(`Data for ${eraseContactRef} has been permanently deleted.`);
    } catch {
      setError('Could not erase contact data. Please try again.');
    } finally {
      setErasingContact(false);
    }
  };

  // ── columns ────────────────────────────────────────────────────────────────

  // ── filtering ──────────────────────────────────────────────────────────────
  const filteredRows = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return rows;
    return rows.filter(r =>
      r.householdRef.toLowerCase().includes(q) ||
      (r.displayName ?? '').toLowerCase().includes(q),
    );
  }, [rows, search]);

  const filteredAdminRows = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return adminRows;
    return adminRows.filter(r =>
      r.householdRef.toLowerCase().includes(q) ||
      (r.displayName ?? '').toLowerCase().includes(q) ||
      (r.phone ?? '').includes(q) ||
      (r.email ?? '').toLowerCase().includes(q),
    );
  }, [adminRows, search]);

  const isAdmin = role === 'admin';

  return (
    <Box>
      {/* header row */}
      <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 2, flexWrap: 'wrap', gap: 1 }}>
        <Box>
          <Typography variant="h6" sx={{ fontWeight: 700 }}>Member Directory</Typography>
          <Typography variant="body2" color="text.secondary">
            {isAdmin
              ? 'Admin view — all active residents including opted-out.'
              : 'Showing residents who have shared their details.'}
          </Typography>
        </Box>
        {!isAdmin && (
          <Button
            variant="outlined"
            startIcon={<ManageAccountsIcon />}
            onClick={() => { setResidentForm(BLANK_RESIDENT); setResidentDialogOpen(true); }}
            sx={{ textTransform: 'none' }}
          >
            My Profile
          </Button>
        )}
      </Box>

      {/* alerts */}
      {toast && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setToast('')}>{toast}</Alert>}
      {error && (
        <Alert
          severity="error"
          sx={{ mb: 2 }}
          action={<Button color="inherit" size="small" startIcon={<RefreshIcon />} onClick={load}>Retry</Button>}
          onClose={() => setError('')}
        >
          {error}
        </Alert>
      )}

      {/* search */}
      <TextField
        size="small"
        placeholder={isAdmin ? 'Search name, apartment, phone, email…' : 'Search residents…'}
        value={search}
        onChange={e => setSearch(e.target.value)}
        sx={{ mb: 2, maxWidth: isAdmin ? 400 : 320 }}
        slotProps={{
          input: {
            startAdornment: (
              <InputAdornment position="start">
                <SearchIcon fontSize="small" />
              </InputAdornment>
            ),
          },
        }}
      />

      <Paper elevation={0} variant="outlined">
        {loading ? (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, p: 4 }}>
            <CircularProgress size={20} />
            <Typography variant="body2" color="text.secondary">Loading directory…</Typography>
          </Box>
        ) : isAdmin ? (
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell sx={{ width: 140 }}>Apartment</TableCell>
                <TableCell sx={{ width: 180 }}>Name</TableCell>
                <TableCell sx={{ width: 150 }}>Phone</TableCell>
                <TableCell sx={{ width: 220 }}>Email</TableCell>
                <TableCell sx={{ width: 110 }}>Opt-out</TableCell>
                <TableCell sx={{ width: 140 }}>Departed</TableCell>
                <TableCell sx={{ width: 120 }} />
              </TableRow>
            </TableHead>
            <TableBody>
              {filteredAdminRows.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} align="center" sx={{ color: 'text.secondary', py: 4 }}>
                    No residents found.
                  </TableCell>
                </TableRow>
              ) : filteredAdminRows.map(r => (
                <TableRow key={r.householdRef}>
                  <TableCell>
                    <Chip label={r.householdRef} size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
                  </TableCell>
                  <TableCell>{r.displayName ?? '—'}</TableCell>
                  <TableCell>{r.phone ?? '—'}</TableCell>
                  <TableCell>{r.email ?? '—'}</TableCell>
                  <TableCell>
                    {r.isOptedOut
                      ? <Chip label="Opted out" size="small" color="warning" />
                      : <Chip label="Active" size="small" color="success" variant="outlined" />}
                  </TableCell>
                  <TableCell>
                    {r.deactivatedAt ? new Date(r.deactivatedAt).toLocaleDateString() : '—'}
                  </TableCell>
                  <TableCell>
                    <Box sx={{ display: 'flex', gap: 0.25 }}>
                      <IconButton size="small" title="Edit" onClick={() => openAdminEdit(r)}>
                        <EditIcon fontSize="small" />
                      </IconButton>
                      <IconButton size="small" color="error" title="Mark Departed" onClick={() => openDepart(r.householdRef)}>
                        <PersonOffIcon fontSize="small" />
                      </IconButton>
                      <IconButton size="small" color="error" title="Erase contact data"
                        onClick={() => { setEraseContactRef(r.householdRef); setEraseContactOpen(true); }}>
                        <DeleteForeverIcon fontSize="small" />
                      </IconButton>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell sx={{ width: 160 }}>Apartment</TableCell>
                <TableCell>Name</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filteredRows.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={2} align="center" sx={{ color: 'text.secondary', py: 4 }}>
                    No residents found.
                  </TableCell>
                </TableRow>
              ) : filteredRows.map(r => (
                <TableRow key={r.householdRef}>
                  <TableCell>
                    <Chip label={r.householdRef} size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
                  </TableCell>
                  <TableCell>{r.displayName ?? '—'}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </Paper>

      {/* resident edit */}
      <EditContactDialog
        open={residentDialogOpen}
        saving={saving}
        form={residentForm}
        onChange={setResidentForm}
        onSave={handleResidentSave}
        onClose={() => setResidentDialogOpen(false)}
        onRequestErase={() => { setResidentDialogOpen(false); setEraseMyOpen(true); }}
      />

      {/* admin edit */}
      <AdminEditDialog
        open={adminEditOpen}
        saving={adminSaving}
        householdRef={adminRef}
        form={adminForm}
        onChange={setAdminForm}
        onSave={handleAdminSave}
        onClose={() => setAdminEditOpen(false)}
      />

      {/* mark departed confirm */}
      <MarkDepartedDialog
        open={departOpen}
        householdRef={departRef}
        departing={departing}
        onConfirm={handleDepart}
        onClose={() => setDepartOpen(false)}
      />

      <EraseMyContactDialog
        open={eraseMyOpen}
        erasing={erasingMy}
        onConfirm={handleEraseMyContact}
        onClose={() => setEraseMyOpen(false)}
      />

      <EraseContactDialog
        open={eraseContactOpen}
        householdRef={eraseContactRef}
        erasing={erasingContact}
        onConfirm={handleEraseContact}
        onClose={() => setEraseContactOpen(false)}
      />
    </Box>
  );
};

export default DirectoryList;
